name: 00 - hello
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout rep
      uses: actions/checkout@v4
    - name: check
      run: ls -la
    - name: print branch
      run: echo "branch is $GITHUB_REF"
      